### ISSUE TITLE
Erster User

### ISSUE THREAD

**Issue by mrtukkin** [robbytobby/kavau#2]
Hey, ich soll kavau für unser Syndikats Projekt aufsetzen, ist aber auch mein erstes Ruby Projekt. Kann natürlich sein, dass das für langjährige Rails User erkennbar ist, aber ohne Docs habe ich einige Schwierigkeiten einen dev Server zu deployen.

Hab es jetzt geschafft einen KaVau Server zu starten und sehe auf localhost die Anmelde Seite.. Aber wie kann ich nun einen neuen User hinzufügen ohne ihn von Hand in die postgres DB eintragen zu müssen?

**Comment by robbytobby** [comment]
Na willkommmen und herzlichen glückwunsch dass du einen development-server am laufen hast. Den ersten User (als admin) mußt du tatsächlich von Hand anlegen. Dafür mußt du aber nicht in postgres eintauchen, sondern die Rails-Console nuzten. 
Einfach im Wurzelverzeichnis deiner installation mit

    bundle exec rails console
die Rails-Console starten. Mit Rails läßt sich dann der User relativ easy anlegen:

    u = User.new(login: 'LOGIN', first_name: 'VORNAME', name: 'NACHNAME', phone: 'TELEFON-NR', role: 'admin', email: 'EMAIL', password: 'PASSWORT', password_confirmation: 'PASSWORT')
    u.save 
Wenn das funktioniert hat erhälst du als Rückgabe auf den Befehl

    => true
und kannst dich mit dem angelegten User im Webbrowser anmelden.
Solltest du aber "false" zurückbekommen, dann ist das speichern des Users gescheitert und du kannst dir mit

    u.errors.messages
die Probleme anschauen um Sie dann zu korrigieren. 
um fehlerhafte Attribute zu korrigieren funktioniert die Syntax:

    u.ATTRIBUT='Neuer Wert'
also z.B.

    u.email = 'foo@bar.org'
speichern mit 
    
    u.save

**Comment by mrtukkin** [comment]
Super vielen Dank @robbytobby
